/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imclient;

import javax.swing.UIManager;
import java.sql.*;
import java.util.Set;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;
import javax.swing.SwingConstants;
import org.jivesoftware.smack.XMPPException;

/**
 *
 * @author Akhil
 */
public class ClientWindow extends javax.swing.JFrame {

    /**
     * Creates new form ClientWindow
     */
    public ClientWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messagePanel = new javax.swing.JPanel();
        sendButton = new javax.swing.JButton();
        messageField = new javax.swing.JTextField();
        chatAreaPane = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JTextArea();
        contactListPane = new javax.swing.JScrollPane();
        contactList = new javax.swing.JList<>();
        typeListArea = new javax.swing.JScrollPane();
        typeList = new javax.swing.JList<>();
        mainMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IM Client");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(905, 630));
        setMinimumSize(new java.awt.Dimension(905, 630));
        setPreferredSize(new java.awt.Dimension(905, 630));
        setResizable(false);
        setSize(new java.awt.Dimension(950, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        messagePanel.setBackground(new java.awt.Color(0, 204, 204));
        messagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sendButton.setBackground(new java.awt.Color(0, 204, 204));
        sendButton.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        sendButton.setText("->");
        sendButton.setContentAreaFilled(false);
        sendButton.setFocusPainted(false);
        sendButton.setRequestFocusEnabled(false);
        sendButton.setRolloverEnabled(false);
        sendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendButtonMouseClicked(evt);
            }
        });
        messagePanel.add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 50, 40));

        messageField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        messagePanel.add(messageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        getContentPane().add(messagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 450, 40));

        chatAreaPane.setBackground(new java.awt.Color(0, 153, 153));
        chatAreaPane.setBorder(null);
        chatAreaPane.setPreferredSize(new java.awt.Dimension(450, 540));

        chatArea.setEditable(false);
        chatArea.setBackground(new java.awt.Color(0, 153, 153));
        chatArea.setColumns(10);
        chatArea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        chatArea.setLineWrap(true);
        chatArea.setRows(5);
        chatAreaPane.setViewportView(chatArea);

        getContentPane().add(chatAreaPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, 540));

        contactListPane.setBackground(new java.awt.Color(0, 102, 102));
        contactListPane.setBorder(null);
        contactListPane.setPreferredSize(new java.awt.Dimension(250, 580));

        contactList.setBackground(new java.awt.Color(0, 102, 102));
        contactList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contactList.setForeground(new java.awt.Color(255, 255, 255));
        contactList.setModel(new DefaultListModel());
        contactList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        contactList.setFixedCellHeight(50);
        contactList.setFixedCellWidth(250);
        contactList.setPreferredSize(new java.awt.Dimension(250, 580));
        contactList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                contactListValueChanged(evt);
            }
        });
        contactListPane.setViewportView(contactList);

        getContentPane().add(contactListPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 250, 580));

        typeListArea.setBorder(null);
        typeListArea.setPreferredSize(new java.awt.Dimension(200, 580));

        typeList.setBackground(new java.awt.Color(0, 51, 51));
        typeList.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        typeList.setForeground(new java.awt.Color(255, 255, 255));
        typeList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Contacts", "Groups" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        typeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        typeList.setFixedCellHeight(50);
        typeList.setFixedCellWidth(200);
        typeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                typeListValueChanged(evt);
            }
        });
        typeListArea.setViewportView(typeList);

        getContentPane().add(typeListArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 580));

        mainMenuBar.setOpaque(false);
        mainMenuBar.setPreferredSize(new java.awt.Dimension(900, 20));

        jMenu1.setText("File");
        jMenu1.setToolTipText("");

        jMenuItem1.setText("Close");
        jMenuItem1.setToolTipText("Closes the IM client");
        jMenuItem1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu1.add(jMenuItem1);

        mainMenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        mainMenuBar.add(jMenu2);

        setJMenuBar(mainMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendButtonMouseClicked
        String message = messageField.getText();
        try{
            xmppManager.sendMessage(message, buddyName+"@"+HOST_NAME);
            DBManager.storeMessage(userName, buddyName, message);
            updateChatArea();
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_sendButtonMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try{
            xmppManager.destroy();
            DBManager.closeConnection();
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_formWindowClosed

    private void contactListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_contactListValueChanged
        ListModel model = contactList.getModel();
        int index = contactList.getSelectedIndex();
        buddyName = model.getElementAt(index).toString().split(":")[0];
        updateChatArea();
    }//GEN-LAST:event_contactListValueChanged

    private void typeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_typeListValueChanged
        Set<String> contacts = xmppManager.getContacts(userName);
        DefaultListModel model = new DefaultListModel();
        for(String s: contacts){
            model.addElement(s);
        }
        contactList.setModel(model);
    }//GEN-LAST:event_typeListValueChanged

    /**
     * Initializes the XMPP manager, performs login for the user and sets
     * the desired status
     * @param username
     * @param password
     * @throws org.jivesoftware.smack.XMPPException
     */
    private void setupManager(String username, String password, String status) throws XMPPException{
        xmppManager = new XmppManager(HOST_NAME, 5222);
        xmppManager.init();
        xmppManager.performLogin(username, password);
        xmppManager.setStatus(true, status);
    }
    
    /**
     * Update the chat to display all messages
     * <p>
     * Erases previous display and redisplays all messages
     */
    private void updateChatArea(){
        try{
            ResultSet rs = DBManager.getMessages(userName, buddyName);
            chatArea.setText("");
            while(rs.next())
                chatArea.append("\n" + rs.getString("sender") + " (" 
                        + rs.getTimestamp("timestamp") + "): " + rs.getString("body"));
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }
    
    /**
     * Creates a thread for the application window
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch(ClassNotFoundException | InstantiationException | 
                IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex){
            java.util.logging.Logger.getLogger(ClientWindow.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ClientWindow window = new ClientWindow();
                
                try{
                    window.setupManager("test_user1", "test_pass1", "Hello everyone");
                    window.userName = "test_user1";
                    DBManager.databaseConnect(DB_NAME, DB_USER, DB_PASSWORD);
                }
                catch(Exception e){
                    System.out.println(e);
                }
                
                //center type list elements
                DefaultListCellRenderer renderer = 
                        (DefaultListCellRenderer) window.typeList.getCellRenderer();
                renderer.setHorizontalAlignment(SwingConstants.CENTER);
                
                //center contact list elements
                renderer = (DefaultListCellRenderer) window.contactList.getCellRenderer();
                renderer.setHorizontalAlignment(SwingConstants.CENTER);
                
                //Make the window visible
                window.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatArea;
    private javax.swing.JScrollPane chatAreaPane;
    private javax.swing.JList<String> contactList;
    private javax.swing.JScrollPane contactListPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JTextField messageField;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JButton sendButton;
    private javax.swing.JList<String> typeList;
    private javax.swing.JScrollPane typeListArea;
    // End of variables declaration//GEN-END:variables

    // Custom variable declaration - can be modified
    private final static String HOST_NAME = "akhil-pc";
    private final static String DB_NAME = "im_db";
    private final static String DB_USER = "im_admin";
    private final static String DB_PASSWORD = "im_password";
    private static XmppManager xmppManager;
    private String userName;
    private String buddyName;
}
