/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imclient;

import java.awt.Color;
import java.awt.Component;
import java.sql.*;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.util.Pair;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.ListModel;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import org.jivesoftware.smack.XMPPException;
import org.jivesoftware.smack.packet.Presence;
import org.jivesoftware.smack.roster.RosterEntry;

/**
 * The outermost layer of the IMClient application
 * <p>
 * Creates a UI for user interaction with IMClient. Database and XMPP server 
 * configurations also included.
 * 
 * @author Akhil
 */
public class ClientWindow extends javax.swing.JFrame {

    /**
     * Creates new form ClientWindow
     */
    public ClientWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messagePanel = new javax.swing.JPanel();
        sendButton = new javax.swing.JButton();
        messageField = new javax.swing.JTextField();
        chatAreaPane = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JTextPane();
        contactListPane = new javax.swing.JScrollPane();
        contactList = new javax.swing.JList<>();
        typeListArea = new javax.swing.JScrollPane();
        typeList = new javax.swing.JList<>();
        mainMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IM Client");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(905, 630));
        setMinimumSize(new java.awt.Dimension(905, 630));
        setPreferredSize(new java.awt.Dimension(905, 630));
        setResizable(false);
        setSize(new java.awt.Dimension(950, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        messagePanel.setBackground(new java.awt.Color(0, 204, 204));
        messagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sendButton.setBackground(new java.awt.Color(0, 204, 204));
        sendButton.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        sendButton.setText("->");
        sendButton.setContentAreaFilled(false);
        sendButton.setFocusPainted(false);
        sendButton.setRequestFocusEnabled(false);
        sendButton.setRolloverEnabled(false);
        sendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendButtonMouseClicked(evt);
            }
        });
        messagePanel.add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 50, 40));

        messageField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        messageField.setBorder(null);
        messagePanel.add(messageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        getContentPane().add(messagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 450, 40));

        chatAreaPane.setBackground(new java.awt.Color(0, 153, 153));
        chatAreaPane.setBorder(null);
        chatAreaPane.setPreferredSize(new java.awt.Dimension(450, 540));

        chatArea.setEditable(false);
        chatArea.setBackground(new java.awt.Color(0, 153, 153));
        chatArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        chatArea.setFocusable(false);
        chatArea.setMargin(new java.awt.Insets(10, 10, 10, 10));
        chatArea.setRequestFocusEnabled(false);
        chatAreaPane.setViewportView(chatArea);

        getContentPane().add(chatAreaPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, 540));

        contactListPane.setBackground(new java.awt.Color(0, 102, 102));
        contactListPane.setBorder(null);
        contactListPane.setPreferredSize(new java.awt.Dimension(250, 580));

        contactList.setBackground(new java.awt.Color(0, 102, 102));
        contactList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contactList.setForeground(new java.awt.Color(255, 255, 255));
        contactList.setModel(new DefaultListModel());
        contactList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        contactList.setAlignmentX(2.0F);
        contactList.setAlignmentY(2.0F);
        contactList.setFixedCellHeight(50);
        contactList.setFixedCellWidth(250);
        contactList.setFocusable(false);
        contactList.setPreferredSize(new java.awt.Dimension(250, 580));
        contactList.setRequestFocusEnabled(false);
        contactList.setSelectionBackground(new java.awt.Color(0, 255, 255));
        contactList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                contactListValueChanged(evt);
            }
        });
        contactListPane.setViewportView(contactList);

        getContentPane().add(contactListPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 250, 580));

        typeListArea.setBorder(null);
        typeListArea.setPreferredSize(new java.awt.Dimension(200, 580));

        typeList.setBackground(new java.awt.Color(0, 51, 51));
        typeList.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        typeList.setForeground(new java.awt.Color(255, 255, 255));
        typeList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Contacts", "Groups" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        typeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        typeList.setFixedCellHeight(50);
        typeList.setFixedCellWidth(200);
        typeList.setFocusable(false);
        typeList.setRequestFocusEnabled(false);
        typeList.setSelectionBackground(new java.awt.Color(0, 204, 204));
        typeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                typeListValueChanged(evt);
            }
        });
        typeListArea.setViewportView(typeList);

        getContentPane().add(typeListArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 580));

        mainMenuBar.setOpaque(false);
        mainMenuBar.setPreferredSize(new java.awt.Dimension(900, 20));

        jMenu1.setText("File");
        jMenu1.setToolTipText("");

        jMenuItem1.setText("Close");
        jMenuItem1.setToolTipText("Closes the IM client");
        jMenuItem1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu1.add(jMenuItem1);

        mainMenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        mainMenuBar.add(jMenu2);

        setJMenuBar(mainMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendButtonMouseClicked
        String message = messageField.getText();
        try{
            xmppManager.sendMessage(message, buddyName+"@"+HOST_NAME);
            DBManager.storeMessage(userName, buddyName, message);
            updateChatArea();
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_sendButtonMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try{
            xmppManager.destroy();
            DBManager.closeConnection();
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_formWindowClosed

    private void contactListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_contactListValueChanged
        ListModel model = contactList.getModel();
        int index = contactList.getSelectedIndex();
        buddyName = model.getElementAt(index).toString().split(":")[0];
        updateChatArea();
    }//GEN-LAST:event_contactListValueChanged

    private void typeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_typeListValueChanged
        updateContactList();
    }//GEN-LAST:event_typeListValueChanged

    /**
     * Initializes the XMPP manager, performs login for the user and sets
     * the desired status
     * @param username
     * @param password
     * @throws org.jivesoftware.smack.XMPPException
     */
    private void setupManager(String username, String password, String status) throws XMPPException{
        xmppManager = new XmppManager(HOST_NAME, 5222);
        xmppManager.init();
        xmppManager.performLogin(username, password);
        xmppManager.setStatus(true, status);
        xmppManager.setWindow(this);
    }
    
    /**
     * Update the chat to display all messages
     * <p>
     * Erases previous display and redisplays all messages
     */
    public void updateChatArea(){
        String previousDate = null;
        try{
            ResultSet rs = DBManager.getMessages(userName, buddyName);
            chatArea.setText("");
            
            //set date display style
            SimpleAttributeSet date = new SimpleAttributeSet();
            StyleConstants.setFontFamily(date, "Tahoma");
            StyleConstants.setForeground(date, Color.WHITE);
            StyleConstants.setAlignment(date, StyleConstants.ALIGN_CENTER);
            StyleConstants.setFontSize(date, 12);
            
            //set username display style
            SimpleAttributeSet user1 = new SimpleAttributeSet();
            StyleConstants.setFontFamily(user1, "Tahoma");
            StyleConstants.setForeground(user1, new Color(0, 0, 204));
            StyleConstants.setAlignment(user1, StyleConstants.ALIGN_LEFT);
            StyleConstants.setFontSize(user1, 16);
            
            SimpleAttributeSet user2 = new SimpleAttributeSet(user1);
            StyleConstants.setForeground(user2, new Color(204, 0, 0));
            
            //set message body display style
            SimpleAttributeSet message = new SimpleAttributeSet();
            StyleConstants.setFontFamily(message, "Tahoma");
            StyleConstants.setForeground(message, Color.BLACK);
            StyleConstants.setAlignment(message, StyleConstants.ALIGN_LEFT);
            StyleConstants.setFontSize(message, 16);
            
            //set time display style
            SimpleAttributeSet time = new SimpleAttributeSet();
            StyleConstants.setFontFamily(time, "Tahoma");
            StyleConstants.setForeground(time, Color.WHITE);
            StyleConstants.setAlignment(time, StyleConstants.ALIGN_RIGHT);
            StyleConstants.setFontSize(time, 10);
            while(rs.next()){
                String[] currentDate = rs.getTimestamp("timestamp").toString().split(" ");
                String user = rs.getString("sender");
                if(previousDate == null){
                    chatArea.setParagraphAttributes(date, true);
                    chatArea.getDocument().insertString(chatArea.getDocument().getLength(),
                            currentDate[0] + "\n", date);
                }
                else if(!previousDate.equals(currentDate[0])){
                    chatArea.setParagraphAttributes(date, true);
                    chatArea.getDocument().insertString(chatArea.getDocument().getLength(),
                            currentDate[0] + "\n", date);
                }
                if(user.equals(userName)){
                    chatArea.setParagraphAttributes(user1, true);
                    chatArea.getDocument().insertString(
                            chatArea.getDocument().getLength(), "You : ", user1);
                }
                else{
                    chatArea.setParagraphAttributes(user2, true);
                    chatArea.getDocument().insertString(
                            chatArea.getDocument().getLength(), user + ": ", user2);
                }
                chatArea.setParagraphAttributes(message, true);
                chatArea.getDocument().insertString(chatArea.getDocument().getLength(),
                        rs.getString("body") + "\n", message);
                chatArea.setParagraphAttributes(time, true);
                chatArea.getDocument().insertString(chatArea.getDocument().getLength(),
                        currentDate[1].substring(0, 5) + "\n", time);
                previousDate = currentDate[0];
            }
        }
        catch(SQLException e){
            System.out.println(e);
        } catch (BadLocationException ex) {
            Logger.getLogger(ClientWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Update the contact list
     */
    public void updateContactList(){
        Set< Pair<RosterEntry, Presence> > contacts = xmppManager.getContacts(userName);
        DefaultListModel model = new DefaultListModel();
        contacts.forEach((c) -> {
            model.addElement(c);
        });
        contactList.setModel(model);
    }
    
    /**
     * Creates a thread for the application window
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ClientWindow window = new ClientWindow();
                window.userName = "test_user1";
                window.password = "test_pass1";
                window.status = "Available";
                try{
                    window.setupManager(window.userName, window.password, window.status);
                    DBManager.databaseConnect(DB_NAME, DB_USER, DB_PASSWORD);
                }
                catch(XMPPException e){
                    System.out.println(e);
                }
                
                //add custom cell renderer to contact List
                window.contactList.setCellRenderer(new ContactListCellRenderer());
                
                //center type list elements
                DefaultListCellRenderer renderer = 
                        (DefaultListCellRenderer) window.typeList.getCellRenderer();
                renderer.setHorizontalAlignment(SwingConstants.CENTER);
                
                //Make the window visible
                window.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane chatArea;
    private javax.swing.JScrollPane chatAreaPane;
    private javax.swing.JList<String> contactList;
    private javax.swing.JScrollPane contactListPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JTextField messageField;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JButton sendButton;
    private javax.swing.JList<String> typeList;
    private javax.swing.JScrollPane typeListArea;
    // End of variables declaration//GEN-END:variables

    // Custom variable declaration - can be modified
    private final static String HOST_NAME = "akhil-pc";
    private final static String DB_NAME = "im_db";
    private final static String DB_USER = "im_admin";
    private final static String DB_PASSWORD = "im_password";
    private static XmppManager xmppManager;
    private String userName;
    private String password;
    private String status;
    private String buddyName;
}

/**
 * A cell renderer for the contact list cells
 * @author Akhil
 */
class ContactListCellRenderer extends JLabel implements ListCellRenderer{
    
    /**
     * Constructor
     */
    public ContactListCellRenderer(){
        setOpaque(true);
        Border margin = new EmptyBorder(10,10,10,10);
        setBorder(margin);
        setHorizontalAlignment(LEFT);
        setVerticalAlignment(CENTER);
    }
    
    /**
     * Returns a JLabel with a username and presence to be added to the JList
     * 
     * @param list          the list which is using the renderer 
     * @param value         the Pair<RosterEntry, Presence> to be rendered
     * @param index         the index of the cell to be rendered
     * @param isSelected    whether the cell to render is selected
     * @param cellHasFocus  whether the cell to render has focus
     * @return 
     */
    @Override
    public Component getListCellRendererComponent(JList list, Object value,
                        int index, boolean isSelected, boolean cellHasFocus){
        //Get the selected index. (The index param isn't
        //always valid, so just use the value.)
        Pair<RosterEntry, Presence> pair = (Pair<RosterEntry, Presence>)value;
        RosterEntry contact = pair.getKey();
        Presence presence = pair.getValue();
        
        if (isSelected) {
            setBackground(list.getSelectionBackground());
            setForeground(list.getSelectionForeground());
        } else {
            setBackground(list.getBackground());
            setForeground(list.getForeground());
        }
        
        setText("<html><span style=\"font-family:Tahoma;font-size:16px;\">"
                + contact.getName()+ "</span><br>" 
                + (presence.isAvailable()? "Online" : "Offline") + "</html>");
        
        return this;
    }
}